
// create new user
POST http://localhost:3001/auth/signup
Content-Type: application/json

  {
    "email": "kakhaa@bl.ru",
    "password": "test@",
    "name": "user1"
  }


### send request for specific user

GET http://localhost:3001/auth/b7130441-79cf-4c66-98c6-fa0ddb9fdbcb
  


### retrieve users vie email

GET http://localhost:3001/auth/?email=kakhaa@bl.ru

### delete user by id

DELETE http://localhost:3001/auth/b7130441-79cf-4c66-98c6-fa0ddb9fdbcb

### update user

PATCH http://localhost:3001/auth/b7130441-79cf-4c66-98c6-fa0ddb9fdbcb
Content-Type: application/json

  {
    "email": "Kakha_updated@bk.ru"
  }